### ISSUE TITLE
redis 'ready' event is not triggered

### ISSUE THREAD

**Issue by puppeteer701** [Grokzen/docker-redis-cluster#122]
Not getting ready event to be triggered. The connected event is triggered but ready is not.

Using ioredis library:
```
      const client = new Cluster(
        [
          {
            host: redisHost,
            port: 7000,
          },
        ],
        {
          dnsLookup: (address, callback) => callback(null, address),
          redisOptions: {
          },
        },
      );

    client.on('ready', () => {
        log.info('Ready to use Redis');
      });

      client.on('connect', () => {
        log.info('Connected to Redis');
      });

      client.on('error', (x) => {
        log.error(`Disconnected from Redis`);
      });
```

Docker compose:
```
  redis-cluster:
    image: grokzen/redis-cluster
    environment:
      MASTERS: 1
      SLAVES_PER_MASTER: 1
    ports:
      - "7000:7000"

```
