### ISSUE TITLE
Wrong redis version used

### ISSUE THREAD

**Issue by kristof-kasa** [Grokzen/docker-redis-cluster#139]
### Environment

* docker-redis-cluster version: 6.0.10
* redis-server version: 6.0.10
* git hash (If applicable): latest
* CLI command used to build the container: `docker-compose up --build redis-cluster`

### Steps to Reproduce

I have the following Dockerfile and docker-compose file.

```Dockerfile
# Dockerfile.redis
FROM grokzen/redis-cluster
```

```yaml
version: '3.8'
services:
  redis-cluster:
    build:
      context: .
      dockerfile: ./Dockerfile.redis
      args:
        - redis_version=6.2.0
    environment:
      - INITIAL_PORT=7000
      - MASTERS=3
      - SLAVES_PER_MASTER=1
      - IP=0.0.0.0
    ports:
     - 7000-7005:7000-7005
```

After the docker-compose build command I ssh into the container I got redis version 6.0.1 instead of 6.2.0

```sh
root@e4bc4c9006af:/data# redis-server --version
Redis server v=6.0.1 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=0
```

### Expected Behavior

When I run `redis-server --version` inside the container I should get 6.2.0

### Observed Behavior

I got back 6.0.1 instead of 6.2.0

**Comment by Grokzen** [comment]
@kristof-kasa You are using the `args` value wrong. Please reference the example file in the repo for exact syntax https://github.com/Grokzen/docker-redis-cluster/blob/master/docker-compose.yml

It should be
```
    build:
      context: .
      args:
        redis_version: '6.2.0'
```
