### ISSUE TITLE
Redis cluster host configuration

### ISSUE THREAD

**Issue by igor-dmitriev** [Grokzen/docker-redis-cluster#37]
Hello, could you help me out? I am trying to configure redis-cluster with Spring Boot Java application, but I can't link my app server with redis cluster, docker-compose:
```
version: '2.1'
services:

app:
    image: my-app
    command: -m 512m
    ports:
     - "8000:8000"
    environment:
      - REDIS_CLUSTER_NODES=redis-cluster:7000,redis-cluster:7001,redis-cluster:7002
    depends_on:
      - redis-cluster

 redis-cluster:
    image: grokzen/redis-cluster:4.0.8
    environment:
     - CLUSTER_ONLY=true
    ports:
     - '7000-7005:7000-7005'
```

but, it does not work, I get:
```
org.springframework.data.redis.RedisConnectionFailureException: Could not get a resource from the pool; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
```
