### ISSUE TITLE
expect 1 Master 2 Slaves with sentinel instead 3 Masters

### ISSUE THREAD

**Issue by kh411d** [Grokzen/docker-redis-cluster#87]
I used this configuration below to create a cluster with 1 master 2 slave with 3 sentinels, but it keeps creating 3 master with no slave attached, what did I do wrong here,
```
version: '2'
services:
  redis-cluster:
    environment:
     IP: '0.0.0.0'
     SENTINEL: 'true'
     MASTERS: 1
     SLAVES_PER_MASTER: 2
    build:
      context: .
      args:
        redis_version: '5.0.5'
    hostname: server
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
```
